# Generated by Django 5.2.18 on 2026-10-07 16:16

import django.db.models.deletion
import django.utils.timezone
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=payments.models.generate_transaction_id, editable=False, max_length=20, unique=True)),
                ('idempotency_key', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('WALLET', 'Wallet')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('card_network', models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('RUPAY', 'RuPay'), ('OTHER', 'Other')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('KOTAK', 'Kotak Mahindra Bank'), ('PNB', 'Punjab National Bank'), ('BOB', 'Bank of Baroda'), ('CANARA', 'Canara Bank'), ('OTHER', 'Other')], max_length=20)),
                ('wallet_provider', models.CharField(blank=True, choices=[('PAYTM', 'Paytm'), ('PHONEPE', 'PhonePe'), ('GOOGLE_PAY', 'Google Pay'), ('AMAZON_PAY', 'Amazon Pay'), ('OTHER', 'Other')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_status', models.CharField(choices=[('PROVIDED', 'Provided'), ('DENIED', 'Permission denied'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=12)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('operating_system', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('fraud_status', models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('LEGITIMATE', 'Legitimate'), ('SUSPICIOUS', 'Suspicious'), ('FRAUDULENT', 'Fraudulent')], default='NOT_CHECKED', max_length=12)),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='txn_user_created_idx'), models.Index(fields=['user', 'status', '-timestamp'], name='txn_user_status_time_idx'), models.Index(fields=['user', 'recipient_email'], name='txn_user_recipient_idx'), models.Index(fields=['user', 'payment_method'], name='txn_user_method_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='txn_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('card_network__gt', ''), ('payment_method', 'CARD')), models.Q(('payment_method', 'UPI'), ('upi_id__gt', '')), models.Q(('bank_name__gt', ''), ('payment_method', 'BANK_TRANSFER')), models.Q(('payment_method', 'WALLET'), ('wallet_provider__gt', '')), _connector='OR'), name='txn_method_details_present'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), _connector='OR'), name='txn_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), _connector='OR'), name='txn_longitude_range'), models.CheckConstraint(condition=models.Q(('fraud_probability__isnull', True), models.Q(('fraud_probability__gte', 0), ('fraud_probability__lte', 1)), _connector='OR'), name='txn_fraud_probability_range'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='txn_user_idempotency_unique')],
            },
        ),
    ]
